# /etc/nginx/sites-available/stripe.azy.solutions
server {
    listen 80;
    server_name stripe.azy.solutions;

    location /webhook/ {
        proxy_pass http://pi6.local:5678/webhook/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
